### ISSUE TITLE
If someone else deploys an nft code, how should I verify that his nft code is from the cw-nfts specification?

### ISSUE THREAD

**Issue by 99Kies** [public-awesome/cw-nfts#129]
If someone else deploys an nft code, how should I verify that his nft code is from the cw-nfts specification?

**Comment by taitruong** [comment]
Not sure what exactly u mean. But you can query for contract's code id (e.g. `starsd query wasm contract CONTRACT_ADDR`), then query for code info (e.g. `starsd query wasm code-info CODE_ID`). Here it returns `data_hash`. Now you can build cw721-base contract - which then returns data hash. This way you can check whether it uses cw721-base contract.

**Comment by 99Kies** [comment]
@taitruong In fact, I would like to discuss whether there is a concept of inheritance on cosmwasm.

like solidity.
```javascript
contract XXXXX is IERC721 {}
```

**Comment by taitruong** [comment]
> @taitruong In fact, I would like to discuss whether there is a concept of inheritance on cosmwasm.
> 
> like solidity.
> 
> ```js
> contract XXXXX is IERC721 {}
> ```

You can easily extend `cw721-base`. Examples here:

- https://github.com/CosmWasm/cw-nfts/tree/main/contracts/cw721-metadata-onchain
- https://github.com/CosmWasm/cw-nfts/tree/main/contracts/cw2981-royalties
