### ISSUE TITLE
Support for extending with CustomQuery 

### ISSUE THREAD

**Issue by hoomp3** [public-awesome/cw-nfts#131]
Hi,

I'd like to use the cw721-base for a chain with a custom query module, but there's no way to extend it in the current implementation. I saw there was already a solution on a fork by Desmos devs a couple months ago.

Any plans to get something like this merged?

https://github.com/desmos-labs/cw-nfts/tree/paul/update-custom-msg-query

**EDIT** I made the necessary changes myself since the previous solution was outdated. Here are the relevant branches.

https://github.com/hoomp3/cw-nfts/tree/feature/cw721-custom-query-ext
https://github.com/hoomp3/cw-plus-plus/tree/feature/cw721-custom-query-ext

**Comment by taitruong** [comment]
Done in #161
