### ISSUE TITLE
migration

### ISSUE THREAD

**Issue by PFC-developer** [public-awesome/cw-nfts#14]
Hi guys.
the cw721-base that was in cw-plus seems to have deviated a bit from what is now in this repo.

any chance of adding a 'migrate' function?

also, if it isn't asking too much, adding a custom 'execute' function to the cw721-metadata-chain contract
so people can see how it's done.

**Comment by JakeHartnell** [comment]
> Hi guys. the cw721-base that was in cw-plus seems to have deviated a bit from what is now in this repo.
> 
> any chance of adding a 'migrate' function?
> 
> also, if it isn't asking too much, adding a custom 'execute' function to the cw721-metadata-chain contract so people can see how it's done.

So, there is a major breaking change that I don't think even a migrate function will solve. Namely, `cw721` is now using `token_uri` like virtually all other NFTs, see #2 for more context.

Previously, the metadata was stored on chain, but now `token_uri` should resolve to a JSON document... which lives off chain (on IPFS for example). Note, you can still migrate on chain metadata but providing a `token_uri` will be challenging for this reason.

See CosmWasm docs for more info on migration: https://docs.cosmwasm.com/docs/1.0/smart-contracts/migration/migration

Perhaps someone else has a sugesstion for how to provide `token_uri` for NFTs during migration.
