### ISSUE TITLE
Extension on mint message

### ISSUE THREAD

**Issue by Morgandri1** [public-awesome/cw-nfts#143]
Why is `Extension` on MintMsg? Shouldnt the extensions be global throughout the contract? 

If not, Extension should be `Option<T>` instead of `T` as this will make development easier.

**Comment by taitruong** [comment]
Imo similar to `Response<T = Empty>`. What we can do is defining `ExecuteMsg<T=Empty, E=Empty>`. Would simplify things.

**Comment by Morgandri1** [comment]
Yeah, and I found that you can define extension as Option<Empty>, but that’s more steps that are subjectively unnecessary, especially when trying to write clean and concise tests

**Comment by taitruong** [comment]
Fixed in #161
