### ISSUE TITLE
Caller is not the contract's current owner

### ISSUE THREAD

**Issue by VegetableDev0701** [public-awesome/cw-nfts#159]
I've developed smart contract using cw-nft. it works well on creator wallet address but it occurs error when works with other wallet address.
This is what issue exactly says.
![image](https://github.com/CosmWasm/cw-nfts/assets/154728112/b1fd14c8-b76f-4b5b-bc52-b85371d5a1c4)

and this is my init function.
![image](https://github.com/CosmWasm/cw-nfts/assets/154728112/03a394d8-0be7-4b0e-bf73-7b4596e4801a)
and this is cargo.toml file
![image](https://github.com/CosmWasm/cw-nfts/assets/154728112/463af15b-6cf4-4276-97cd-857c5354e588)

Please help me on this asap.

**Comment by JakeHartnell** [comment]
Not enough info to debug.
