### ISSUE TITLE
Unable to paginate queries

### ISSUE THREAD

**Issue by iLoveBusinessDevelopment** [public-awesome/cw-nfts#16]
It seems like the `all_approvals` and the `all_tokens` have an issue with pagination.

Both of them call `maybe_addr` on the `start_after`, when in reality we just want to treat `start_after` as a token id that isn't an address.

The tests pass because `api.addr_validate` seems to not throw an error with `MockApi`, and instead will let the token id pass right through. But when deployed on-chain, `addr_validate` will throw an error, which stops people from being able to paginate. 

Proposed solution:

in `contracts/cw721-base/src/query.rs`, remove all instances of `maybe_addr`, just use `start_after` in place of `start_addr`.

Am I reading this right? @ethanfrey

**Comment by iLoveBusinessDevelopment** [comment]
just saw https://github.com/CosmWasm/cw-plus/pull/491, porting over now

**Comment by maurolacy** [comment]
Just to be clear, `all_tokens` had the bug (fixed by #491).

`all_approvals` is correct, in that both parameters (`owner` and `start_after`) _are_ addresses.

**Comment by evandekieft** [comment]
Hey @JakeHartnell - for developers that want to interface with arbitrary NFTs on chain, is there any way to work around this from the client side so both old broken contracts like Galactic Punks & LunaBulls as well as newer ones with this fix can be queried?

**Comment by yubrew** [comment]
> Hey @JakeHartnell - for developers that want to interface with arbitrary NFTs on chain, is there any way to work around this from the client side so both old broken contracts like Galactic Punks & LunaBulls as well as newer ones with this fix can be queried?

I believe old contracts need to be migrated, which can only be done by the contract admin, in order to take advantage of new pagination functionality.
