### ISSUE TITLE
Transfer ownership of this repo to public-awesome (Stargaze)

### ISSUE THREAD

**Issue by webmaster128** [public-awesome/cw-nfts#163]
Hi everyone,

it is great to see how this repository is flourishing and the ecosystem is growing. As we (Confio) do not have a team that can reasonably work on domain specific standards such as NFTs, it is time to hand this repo over. This is part of a larger cleanup initiative of the CosmWasm organization that aims to increase security and communication around maintenance. 

Stargaze and Ark Protocol are some of the most active contributors here. Fortunately the Stargaze team volumteered to host this repo in the future. Thank you for that! So Shane and me propose to move this repo to [public-awesome](https://github.com/public-awesome), a better home for NFT related code. We want to ensure all redirects in the web and in git work to make the transitions as smooth as possible.

Any objections or other thoughts?

Also could someone please provide a list of crates from this codebase such that I can check permissions on crates.io?

**Comment by JakeHartnell** [comment]
+1 from me.

Crates I know of:
- [cw721](https://crates.io/crates/cw721)
- [cw721-base](https://crates.io/crates/cw721-base)
- [cw721-metadata-onchain](https://crates.io/crates/cw721-metadata-onchain)
- [cw721-non-transferable](https://crates.io/crates/cw721-non-transferable)
- [cw2981-royalties](https://crates.io/crates/cw2981-royalties)

**Comment by webmaster128** [comment]
The transfer route is a bit complicated as neither me nor Shane are admin of both orgs.

1. Transfer from CosmWasm to webmaster128 ✅ 
1. Transfer from webmaster128 to shanev ✅ 
3. Transfer from shanev to public-awesome ✅

**Comment by webmaster128** [comment]
Done, thanks a lot everyone
