### ISSUE TITLE
Make CW721 equivalent to ERC721-Metadata

### ISSUE THREAD

**Issue by iLoveBusinessDevelopment** [public-awesome/cw-nfts#2]
The current implementation of CW721 is not directly compatible with ERC721 with metadata. The proposal is to remove some fields and add a `token_uri` field for a metadata extension.

Collection-wide fields for CW721:
- name (name of the NFT collection)
- symbol (symbol of NFT collection)

For each `TokenId` expect it to point to one field `token_uri`, like [ERC721](https://docs.openzeppelin.com/contracts/4.x/api/token/erc721#IERC721Metadata)

So mint would look like this:
```
#[derive(Serialize, Deserialize, Clone, Debug, PartialEq, JsonSchema)]
pub struct MintMsg {
    /// Unique ID of the NFT
    pub token_id: String,
    /// The owner of the newly minter NFT
    pub owner: String,
    /// A distinct Uniform Resource Identifier (URI) for a given asset.
    pub token_uri: String,
}
```

We expect the `token_uri` to point to a JSON file that conforms to the CW721 JSON schema (a direct copy of the ERC721 JSON schema):
```
{
    "title": "Asset Metadata",
    "type": "object",
    "properties": {
        "name": {
            "type": "string",
            "description": "Identifies the asset to which this NFT represents"
        },
        "description": {
            "type": "string",
            "description": "Describes the asset to which this NFT represents"
        },
        "image": {
            "type": "string",
            "description": "A URI pointing to a resource with mime type image/* representing the asset to which this NFT represents. Consider making any images at a width between 320 and 1080 pixels and aspect ratio between 1.91:1 and 4:5 inclusive."
        }
    }
}
```
This where the fields `name`, `description`, and `image` go. Individual NFT creators can then add new JSON fields to extend their NFT:

For example adding an `attributes` field to support traits:

```
{
    "name": "name-of-my-asset",
    "description": "description-of-my-asset",
    "image": "image-url",
    "attributes": [
        {
          "trait_type": "Name of some trait", 
          "value": "Value of some trait"
        }, 
    ]
}
```
In general, extensions to the CW721 JSON schema should follow the [opensea metadata standard](https://docs.opensea.io/docs/metadata-standards).

With cross chain initiatives and NFT bridges coming, we want to be able to bridge Ethereum NFTs to chains running CosmWasm, and the best way to enable this is to ensure there is a simple mapping between ERC721 and CW721. I would be happy to make this change (as well as a similar change to CW1155), if the devs think this is reasonable.

**Comment by JakeHartnell** [comment]
Extension is crucial IMO (it's going to open up new possibilities), but it certainly makes sense to conform to the metadata standard for interoperability. Like the proposal @alwin-peng, also great to have types for common metadata standards like OpenSea. :100: 

Example `MintMsg`:
```rust
#[derive(Serialize, Deserialize, Clone, Debug, PartialEq, JsonSchema)]
pub struct MintMsg<T> {
    /// Unique ID of the NFT
    pub token_id: String,
    /// The owner of the newly minter NFT
    pub owner: String,
    /// A distinct Uniform Resource Identifier (URI) for a given asset.
    pub token_uri: String,
    /// Custom stuff here
    pub extension: T,
}
```

Feel the only things that really belong in `TokenInfo` are `token_id`, `owner`, and `token_uri`. Some NFTs may lack a description / image, or even a name... the extension can handle all of those custom fields.

**Comment by JakeHartnell** [comment]
> Maybe we can even generate a URL so open sea could read the on chain data as JSON.

This is a really interesting idea @ethanfrey... not sure the best way to do this.

**Comment by iLoveBusinessDevelopment** [comment]
gonna make a PR moving name/image/description to an extension and adding `token_uri`. i think `token_uri` should also be optional, so its interoperable with base ERC721
