### ISSUE TITLE
all_tokens query / start_after parameter

### ISSUE THREAD

**Issue by PFC-developer** [public-awesome/cw-nfts#22]
should this really be a 'address' 
my immediate thought when I looked at this, was that this should be fetching X tokens after the token_id.
and the token_id can be a string.

**Comment by petes-fan-club** [comment]
let tokens: StdResult<Vec<String>> = self
            .tokens
            .range(deps.storage, start, None, Order::Ascending)
            .take(limit)
            .map(|item| item.map(|(k, _)| String::from_utf8_lossy(&k).to_string()))
            .collect();
            
           is how it is written today
would it be better off doing something like
     let tokens: StdResult<Vec<String>> = self
            .tokens
            .skip_idx(deps.storage, start, None, Order::Ascending)
            .take(limit)
            .map(|item| item.map(|(k, _)| String::from_utf8_lossy(&k).to_string()))
            .collect();

and make 'start' a number ?

**Comment by PFC-developer** [comment]
```
    fn page_tokens(
        &self,
        deps: Deps,
        start_after: Option<String>,
        limit: Option<u32>,
    ) -> StdResult<TokensResponse> {
        let limit = limit.unwrap_or(DEFAULT_LIMIT).min(MAX_LIMIT) as usize;
        let start = start_after.map(|addr| Bound::exclusive(addr.as_bytes()));
        let tokens: StdResult<Vec<String>> = self
            .tokens
            .range(deps.storage, start, None, Order::Ascending)
            .take(limit)
            .map(|item| item.map(|(k, _)| String::from_utf8_lossy(&k).to_string()))
            .collect();
        Ok(TokensResponse { tokens: tokens? })
    }

```
can't do a PR right now.. but this is what I was thinking

**Comment by JakeHartnell** [comment]
This has been fixed in the latest version: https://github.com/CosmWasm/cw-nfts/blob/main/contracts/cw721-base/src/query.rs#L107
