### ISSUE TITLE
Update to cw-plus v0.11

### ISSUE THREAD

**Issue by ethanfrey** [public-awesome/cw-nfts#39]
Mentioned here: https://github.com/CosmWasm/cw-nfts/pull/27#issuecomment-1002236943

It would be good to follow cw-plus release, and then push out cw721 v0.11.0 soon.
Happy if you move faster than cw-plus, but let's keep the latest version usable.

(This was release shortly before holidays, so no pressure to have it already, just think this is a good update to prioritise in the new year, and also meshes with importing cw1155)

**Comment by JakeHartnell** [comment]
@orkunkl, think you can help with this? :pray:

**Comment by ethanfrey** [comment]
Please see https://github.com/CosmWasm/cw-plus/blob/main/MIGRATING.md#v0103---v0110

Major issues are if you used (signed) ints as a key, and also moving `Map.range` to accept a parsed key rather than unparsed bytes as the first element. Also some different syntax for MultiIndex.

The author of much of this is on vacation til next week, so if it gets tricky, better to wait a few days
