### ISSUE TITLE
Invalid contract name for cw721-metadata-onchain 

### ISSUE THREAD

**Issue by giansalex** [public-awesome/cw-nfts#44]
Currently metadata-onchain contract returns same cw721-base package name, but should be return its [crates name](https://crates.io/crates/cw721-metadata-onchain) : `crates.io:cw721-metadata-onchain`.

https://github.com/CosmWasm/cw-nfts/blob/d1a36319da1a432e0dd5ffe5c7dbb2e03a6777b6/contracts/cw721-base/src/execute.rs#L14

Maybe contrac_name should be set as contract_version and take name from `CARGO_PKG_NAME` 
https://github.com/CosmWasm/cw-nfts/blob/d1a36319da1a432e0dd5ffe5c7dbb2e03a6777b6/contracts/cw721-base/src/execute.rs#L15

**Comment by the-frey** [comment]
Yeah, looks like all the contracts inherit the instantiate method & thus the name. This could be an issue when migrating, for example.

Solution is maybe to parameterize instantiate on the base contract so that the correct name can be passed in.

**Comment by giansalex** [comment]
@the-frey yes, it is a solution.

**Comment by the-frey** [comment]
@giansalex thoughts on this? https://github.com/CosmWasm/cw-nfts/pull/45#issuecomment-1024149760
