### ISSUE TITLE
cannot deploy a fresh git clone

### ISSUE THREAD

**Issue by gnomadic** [public-awesome/cw-nfts#57]
```
➜  cw-nfts git:(main) ✗ terrad version
0.5.17
```

Any other local versions would be useful to share?

steps to reproduce:

```
~git clone git@github.com:CosmWasm/cw-nfts.git
~cd cw-nfts

~cargo build

~docker run --rm -v "$(pwd)":/code \
  --mount type=volume,source="$(basename "$(pwd)")_cache",target=/code/target \
  --mount type=volume,source=registry_cache,target=/usr/local/cargo/registry \
  cosmwasm/rust-optimizer:0.12.3
```
<--- Everything is successful so far --->

```
~terrad tx wasm store artifacts/cw721_metadata_onchain.wasm --from test1 --chain-id=localterra --gas=auto --fees=100000uluna --broadcast-mode=block

```

fails with:

Error: rpc error: code = InvalidArgument desc = failed to execute message; message index: 0: Error calling the VM: Error during static Wasm validation: Wasm contract has unknown interface_version_* marker export (see https://github.com/CosmWasm/cosmwasm/blob/main/packages/vm/README.md): store wasm contract failed: invalid request

**Comment by gnomadic** [comment]
Ah I see https://github.com/CosmWasm/cosmwasm/issues/1190

Looks like it's a terra limitation.

Is there any problems we should expect if we fork this repo, downgrade the incompatible dependencies, and use it with terra?

**Comment by JakeHartnell** [comment]
Closing as stale.
