### ISSUE TITLE
How to make a Querier

### ISSUE THREAD

**Issue by arlicle** [public-awesome/cw-nfts#63]
I want query cw721-base contract on other contract,  It's need a arg querier, How can I make a querier?

```
    pub fn query<T: DeserializeOwned>(
        &self,
        querier: &QuerierWrapper,
        req: QueryMsg,
    ) -> StdResult<T> {
        let query = WasmQuery::Smart {
            contract_addr: self.addr().into(),
            msg: to_binary(&req)?,
        }
        .into();
        querier.query(&query)
    }
```

**Comment by JakeHartnell** [comment]
Please ask CosmWasm programming questions in the main CosmWasm discord: https://discord.gg/Hzpfq9rD

If you're trying to query in an execute or query method with access to [Deps](https://docs.rs/cosmwasm-std/latest/cosmwasm_std/struct.Deps.html), would look something like so:
```rust
let resp: NumTokensResponse = deps.querier.query_wasm_smart(
                        &cw721_contract_address,
                        &Cw721QueryMsg::NumTokens {},
                    )?;
```
