### ISSUE TITLE
Move entry_point flag onto entry functions for cw721-base

### ISSUE THREAD

**Issue by Callum-A** [public-awesome/cw-nfts#74]
Makes the contract multitestable and in line with other contract structures.

**Comment by 0xekez** [comment]
Was writing this up elsewhere, but realize it's only needed here. Reason we need to do this:

Cargo uses [feature unification](https://doc.rust-lang.org/cargo/reference/features.html#feature-unification) during dependency compilation. During feature unification, cargo determines the union (set theory edition) of all the features set for a given crate and compiles _one_ version of that library with those features enabled. The top level crate or workspace then is linked against this unified library.

From the docs:

> A consequence of this is that features should be additive. That is, enabling a feature should not disable functionality.

As it is currently the case the enabling the `library` feature _removes_ methods this confuses cargo and results in it being impossible to both use cw721 messages in your contract and use it's execute methods in a test.

**Comment by JakeHartnell** [comment]
Closed with #76
